.travis.yml, frontend/.eslintrc.js, frontend/package-lock.json, frontend/package.json
=> eslint-travis

.travis.yml
=> [setting] travis CI Setting

.travis.yml, backend/requirements.txt, backend/sonar-project.properties, backend/triplannet/user/views.py, frontend/sonar-project.properties, sonar-project.properties
Origin: django ver 2.2.6
->
Now: django ver 2.1.*
This caused by sqlite3 build error.
=> [Setting] backend requirements

.travis.yml, README.md
=> Modify .travis.yml for coveralls setting

frontend/package.json, frontend/src/App.js, frontend/src/components/travel-overview/TravelOverviewList.js, frontend/src/containers/travel-overview/PopularTravelOverviewList.test.js, frontend/src/containers/travel-overview/RecentTravelOverviewList.test.js, frontend/src/containers/travel-overview/SearchTravelOverviewList.js, frontend/src/containers/travel-overview/SearchTravelOverviewList.test.js, frontend/src/pages/MainPage.js, frontend/src/pages/MainPage.test.js, frontend/src/pages/SearchPage.js, frontend/src/pages/SearchPage.test.js, frontend/yarn.lock
Query string은 /search?tag=keyword와 같은 방식으로 들어옵니다.
=> Search page

frontend/.eslintrc.js, frontend/src/App.js, frontend/src/components/travel-overview/TravelOverviewList.js, frontend/src/components/travel-settings/CollaboratorSetting.js, frontend/src/components/travel-settings/TravelSetting.js, frontend/src/components/user-info/UserInfoSection.js, frontend/src/containers/travel-overview/OneTravelOverview.js, frontend/src/containers/travel-overview/OneTravelOverview.test.js, frontend/src/containers/travel-overview/PopularTravelOverviewList.test.js, frontend/src/containers/travel-overview/RecentTravelOverviewList.test.js, frontend/src/containers/travel-overview/SearchTravelOverviewList.test.js, frontend/src/containers/travel-overview/UserTravelOverviewList.test.js, frontend/src/containers/travel-settings/CollaboratorSettingContainer.js, frontend/src/containers/travel-settings/CollaboratorSettingContainer.test.js, frontend/src/containers/travel-settings/TravelSettingContainer.js, frontend/src/containers/travel-settings/TravelSettingContainer.test.js, frontend/src/containers/user-info/UserInfoSectionContainer.test.js, frontend/src/pages/TravelSettingsPage.js, frontend/src/pages/TravelSettingsPage.test.js
=> TravelSettingsPage

frontend/src/App.js, frontend/src/components/user-info-edit/EditUserInfo.js, frontend/src/containers/user-info-edit/EditUserInfoContainer.js, frontend/src/containers/user-info-edit/EditUserInfoContainer.test.js, frontend/src/pages/EditUserInfoPage.js, frontend/src/pages/EditUserInfoPage.test.js
=> [Frontend] Edit User Info Page

frontend/src/App.js, frontend/src/App.test.js, frontend/src/components/travelblock/TravelActivityBlockView.js, frontend/src/components/travelblock/TravelActivityBlockView.test.js, frontend/src/components/travelblock/TravelDayBlockView.js, frontend/src/components/travelblock/TravelDayBlockView.test.js, frontend/src/containers/travelDetail/TravelDetail.js, frontend/src/pages/TravelDetail.js, frontend/src/pages/TravelDetail.test.js, frontend/src/store/actions/index.js, frontend/src/store/actions/travel.js, frontend/src/store/reducers/travel.js, frontend/src/store/reducers/travel.test.js, frontend/src/store/store.js
=> [Frontend] Travel Detail Page

frontend/src/components/travel-overview/TravelOverviewBlock.js, frontend/src/components/travel-overview/TravelOverviewBlock.test.js, frontend/src/components/travel-overview/TravelOverviewList.test.js, frontend/src/containers/travel-overview/OneTravelOverview.test.js, frontend/src/containers/travel-overview/PopularTravelOverviewList.js, frontend/src/containers/travel-overview/PopularTravelOverviewList.test.js, frontend/src/containers/travel-overview/RecentTravelOverviewList.js, frontend/src/containers/travel-overview/RecentTravelOverviewList.test.js, frontend/src/pages/MainPage.js, frontend/src/store/actions/actionTypes.js, frontend/src/store/actions/index.js, frontend/src/store/actions/travel.js, frontend/src/store/reducers/travel.js, frontend/src/store/reducers/travel.test.js
- Popular travel overview 백엔드와 연결, travel reducer 추가구현
- Recent travel overview 백엔드와 연결, travel reducer 추가구현
=> Popular travel reducer

backend/triplannet/travel/serializers.py, backend/triplannet/travel/views.py, frontend/yarn.lock
- POST travel API 수정 
head가 null인 travel post시 error 발생시키도록 수정
- GET travel/recent & travel/popular
head가 null인 travel을 제외하고 가져오도록 수정
=> Fix alpha test error

backend/triplannet/user/urls.py, backend/triplannet/user/views.py, frontend/src/containers/common/HeaderContainer.js
Header 검색창에 @+usernickname으로 user 검색이 가능합니다.
Demo video용으로 급하게 구현했습니다.
=> [Frontend & Backend] User Search

frontend/src/store/actions/travel.js
현재 master branch의 build fail의 원인이 되는 eslint error 수정하였습니다.
=> [Hotfix] Fix eslint errors

backend/triplannet/travel/views.py, frontend/src/containers/travel-overview/RecommendedTravelOverviewList.js, frontend/src/containers/travelDetail/CommentsLikeContainer.js, frontend/src/store/actions/travel.js
Recommendation feature backend frontend 연결해서 잘 작동합니다.
View랑 like도 클릭하면 backend에 잘 반영됩니다.
=> [Backend/Frontend] Recommendation feature applied to service

backend/triplannet/travel/models.py, backend/triplannet/travel/urls.py, backend/triplannet/travel/views.py, frontend/src/containers/createTravel/CreateTravel.js, frontend/src/store/actions/travel.js
- Edit photo 관련 버그 수정
- GET travel API 수정 ( user별로 다른 결과 보여주도록 )
=> [Frontend & Backend] Edit travel

backend/triplannet/travel/views.py
change the recommend to show previously viewed plan
=> [Backend] Recommendation subtle change on previously viewed plan

backend/triplannet/user/tests.py
=> [Backend] some user test implemented

backend/triplannet/user/tests.py, frontend/src/containers/auth/LoginForm.test.js
=> [Frontend] Login form test

backend/triplannet/user/tests.py, frontend/src/containers/auth/LoginForm.test.js, frontend/src/store/actions/travel.test.js
travel action - create travel test added
=> Travel action test

frontend/src/components/travel-overview/TravelOverviewBlock.js, frontend/src/components/travel-overview/TravelOverviewBlock.test.js, frontend/src/containers/travel-overview/PopularTravelOverviewList.js, frontend/src/containers/travel-overview/RecentTravelOverviewList.js, frontend/src/containers/travel-overview/UserTravelOverviewList.test.js, frontend/src/containers/user-info-edit/EditUserInfoContainer.test.js
src/components/travel-overview/TravelOverviewBlock.js
=> [Frontend] SJW frontend testing 2

backend/requirements.txt, frontend/package.json, frontend/yarn.lock
- django
- serialize-javascript
=> Fix security alert
